name: investify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get:
  sqflite:
  path_provider:
  flutter_native_splash:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/font/ubuntu/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/ubuntu/Ubuntu-Regular.ttf
          weight: 500
        - asset: assets/font/ubuntu/Ubuntu-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/font/ubuntu/Ubuntu-Medium.ttf
          weight: 400
        - asset: assets/font/ubuntu/Ubuntu-MediumItalic.ttf
          weight: 400
          style: italic
        - asset: assets/font/ubuntu/Ubuntu-Light.ttf
          weight: 200
        - asset: assets/font/ubuntu/Ubuntu-LightItalic.ttf
          weight: 200
          style: italic
